### ISSUE TITLE
After updating vscode, the icons have become smaller

### ISSUE THREAD

**Issue by wy916787036** [vtrois/gitmoji-vscode#23] opened 2021-05-07 03:48 UTC
vscode version: 1.56.0
os: windows10
![](https://i.loli.net/2021/05/07/V9E1Fwgc8yZWLMl.png)

**Comment by seatonjiang** [comment] 2021-05-07 08:38
I was unable to reproduce this issue, please try reinstalling Gitmoji.

![image](https://user-images.githubusercontent.com/57834639/117422700-7cbef300-af52-11eb-8d43-428aa745a362.png)

**Comment by KaitoHH** [comment] 2021-05-07 10:52
I have the same problem. I think this problem occurs when there are multiple submodules in one project, where the icon will be appearing at the sub-panel, not the source control panel.
![未命名](https://user-images.githubusercontent.com/13927774/117439335-4ccd1b00-af65-11eb-84bc-ab851541b835.png)

**Comment by wy916787036** [comment] 2021-05-08 04:42
The icon only gets smaller when there are multiple items
![](https://i.loli.net/2021/05/08/eoU3WkNMpHgRYtF.png)
Then I found this css is overriding the height of the icon to make it smaller

**Comment by yi-Xu-0100** [comment] 2021-05-13 08:30
https://github.com/microsoft/vscode/issues/123041

**Comment by seatonjiang** [comment] 2021-05-13 08:42
Thanks to @yi-Xu-0100  for introducing the issues, this is indeed a VSCode problem, just wait for the new VSCode version to be updated.
@KaitoHH @wy916787036

**Comment by KaitoHH** [comment] 2021-05-14 09:33
FYI, the problem has been fixed in 1.56.2

![image](https://user-images.githubusercontent.com/13927774/118251575-58c35a80-b4da-11eb-9919-145321ce7243.png)

**Closed** 2021-05-25 08:54 UTC
